title: Bootstrap 4 Github Pages
email: "benjaminforbesgriffith@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  BFGriffith’s photography portfolio and travelogue
#baseurl: ""
url: "https://bfgriffith.github.io/fotoj/"
twitter_username: BFGriffith
github_username:  BFGriffith

repository: "BFGriffith/fotoj"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
